/*
 *
 * Sepage constants
 *
 */

export const CHANGE_SEARCHBOX = 'app/Sepage/CHANGE_SEARCHBOX';
export const GET_GENRE_PREDICTION_REQUESTED = 'app/Sepage/GET_GENRE_PREDICTION_REQUESTED';
export const GET_GENRE_PREDICTION_SUCCESS = 'app/Sepage/GET_GENRE_PREDICTION_SUCCESS';
export const GET_GENRE_PREDICTION_ERROR = 'app/Sepage/GET_GENRE_PREDICTION_ERROR';
